version: '3.8'

services:
  discord-bot:
    build: .
    container_name: fsociety-discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./.env:/app/.env:ro
    ports:
      - "8000:8000" 