services:
  - type: web
    name: fsociety-discord-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    # Add better restart policy
    restartPolicy: always 