services:
  - type: web
    name: fsociety-discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
    healthCheckPath: /
    autoDeploy: true 