services:
  - type: web
    name: fsociety-discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
    plan: free 