services:
  - type: web
    name: fsociety-discord-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://fsociety-discord-bot.onrender.com 